image: gradle:jre11-slim

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - ./gradlew clean build
        - ./gradlew pmdMain
        - ./gradlew pmdTest
        - ./gradlew checkstyleMain
        - ./gradlew checkstyleTest
    artifacts:
        paths:
            - build/libs/*.jar
