image: gradle:jre11-slim
services:
    - docker:dind

variables:
    SPRING_PROFILES_ACTIVE: gitlab-ci
    DOCKER_DRIVER: overlay2

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - ./gradlew clean build
        - ./gradlew pmdMain
        - ./gradlew pmdTest
        - ./gradlew checkstyleMain
        - ./gradlew checkstyleTest
    artifacts:
        paths:
            - build/libs/*.jar

heroku-push:
    stage: deploy
    image: docker:latest
    script:
        - docker build -f Dockerfile --iidfile imageid.txt -t registry.heroku.com/conference-service .
        - docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
        - docker push registry.heroku.com/conference
        - apk add --no-cache curl
        - echo "Docker Image ID is $(cat imageid.txt)"
        - |-
            curl -X PATCH https://api.heroku.com/apps/conference-service/formation --header "Content-Type: application/json" --header "Accept: application/vnd.heroku+json; version=3.docker-releases" --header "Authorization: Bearer ${HEROKU_API_KEY}" --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat imageid.txt)'" } ] }'
